Text Representation

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['pepole wath cricket','player was player','people write comvment','cricket play comment'],'output':[1,1,0,0]})

In [3]:
df

                    text  output
0    pepole wath cricket       1
1      player was player       1
2  people write comvment       0
3   cricket play comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer()

In [7]:
bow  = cv.fit_transform(df['text'])

In [8]:
print(cv.vocabulary_)

{'pepole': 4, 'wath': 8, 'cricket': 2, 'player': 6, 'was': 7, 'people': 3, 'write': 9, 'comvment': 1, 'play': 5, 'comment': 0}

In [9]:

print(bow[0].toarray())

print(bow[1].toarray())

[[0 0 1 0 1 0 0 0 1 0]]
[[0 0 0 0 0 0 2 1 0 0]]

In [11]:
cv.transform(['cricket wath and write comment of cricket comment']).toarray()

array([[2, 0, 2, 0, 0, 0, 0, 0, 1, 1]])

In [12]:
# 2.N-gram

In [13]:
v = CountVectorizer(ngram_range=(1,2))

In [14]:
bow  = v.fit_transform(df['text'])

In [15]:
df['text']

0      pepole wath cricket
1        player was player
2    people write comvment
3     cricket play comment
Name: text, dtype: object

In [16]:
# vocob
print(v.vocabulary_)

{'pepole': 6, 'wath': 14, 'cricket': 2, 'pepole wath': 7, 'wath cricket': 15, 'player': 10, 'was': 12, 'player was': 11, 'was player': 13, 'people': 4, 'write': 16, 'comvment': 1, 'people write': 5, 'write comvment': 17, 'play': 8, 'comment': 0, 'cricket play': 3, 'play comment': 9}

In [17]:
# TF(term frequency)
# IDF(Inverse document frequencey)

In [18]:
#TF(t,d) = (Number of occurence of term t in document d)/
#(total number of term in the document d)
#ex = 

#d1 = people watch cricket.

#tf(people,d1) = 1/3

#d2 = match was match
#tf(match,d2) = 2/3

In [19]:
# IDF(t) = loge(total number of  documnet in the corpus)/
#(number of document with term t in them)
#ex == 

#d1 = people watch cricket.
#d2 = cricket was cricket.
#d3 = people write comment.
#d4 = cricket write comment.

#idf(cricket) = Log(4/4)
#idf(people) = Log(4/2)

In [20]:
# we can use by apply feature_extraction methode in skleran

In [21]:
df

                    text  output
0    pepole wath cricket       1
1      player was player       1
2  people write comvment       0
3   cricket play comment       0

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.48693426, 0.        , 0.61761437,
        0.        , 0.        , 0.        , 0.61761437, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.89442719, 0.4472136 , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        , 0.57735027, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.57735027],
       [0.61761437, 0.        , 0.48693426, 0.        , 0.        ,
        0.61761437, 0.        , 0.        , 0.        , 0.        ]])

In [23]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.91629073 1.91629073 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073 1.91629073 1.91629073]
['comment' 'comvment' 'cricket' 'people' 'pepole' 'play' 'player' 'was'
 'wath' 'write']