In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\ss\Desktop\\DL_REGEX\\ANN\\Attrition - Attrition.csv")

In [3]:
df.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7

In [4]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [5]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [6]:
df = df.dropna()

In [7]:
x = df.drop(columns=['Attrition'],axis=1)
y = df['Attrition']

In [8]:
categorical_feature = ['BusinessTravel',
                       'Department',
                       'EducationField',
                       'Gender',
                       'JobRole',
                       'MaritalStatus',
                       'Over18',
                       'OverTime']

In [9]:
x_encoded = pd.get_dummies(x,columns = categorical_feature,drop_first=True)

In [10]:
x_encoded = x_encoded.astype(int)

In [11]:
lb = LabelEncoder()

In [12]:
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(
    x_encoded,
    y_encoded,
    test_size=0.2,
    random_state=42
)

In [15]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [16]:
sc = StandardScaler()

In [17]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.fit_transform(x_test)

now we will create architecture of our model

In [18]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',input_dim = x_train_scaled.shape[1]),  #input
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64,activation='relu'),  #hidden
    tf.keras.layers.Dense(units=1,activation='sigmoid')  #output
])

c:\Users\ss\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

compile the model

In [19]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [20]:
import tensorflow as tf

learning_rate = 0.001
momentum = 0.9

optimizer = tf.keras.optimizers.SGD(
    learning_rate=learning_rate,
    momentum=momentum,
    nesterov=True
)

In [21]:
model.compile(optimizer=optimizer,loss = loss_fn,metrics = metrics)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

train the model

In [22]:
model.fit(x_train_scaled,y_train,epochs = 50,batch_size = 8,validation_split = 0.1)

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7873 - loss: 0.5021 - val_accuracy: 0.8051 - val_loss: 0.4528
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8365 - loss: 0.4326 - val_accuracy: 0.7966 - val_loss: 0.4254
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8374 - loss: 0.4095 - val_accuracy: 0.7966 - val_loss: 0.4117
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8374 - loss: 0.3847 - val_accuracy: 0.7966 - val_loss: 0.3981
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8469 - loss: 0.3827 - val_accuracy: 0.8051 - val_loss: 0.3906
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8544 - loss: 0.3595 - val_accuracy: 0.8305 - val_loss: 0.3841
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8573 - loss: 0.3383 - val_accuracy: 0.8559 - val_loss: 0.3772
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8592 - loss: 0.3363 - val_accuracy: 0.8559 - val_loss: 0.3749
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8677 - loss: 0.3260 - val_accuracy: 0.8644 - val_loss: 0.3697
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8724 - loss: 0.3127 - val_accuracy: 0.8559 - val_loss: 0.3708
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8771 - loss: 0.2976 - val_accuracy: 0.8644 - val_loss: 0.3723
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8752 - loss: 0.2954 - val_accuracy: 0.8559 - val_loss: 0.3729
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8819 - loss: 0.2995 - val_accuracy: 0.8559 - val_loss: 0.3694
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8894 - loss: 0.2850 - val_accuracy: 0.8559 - val_loss: 0.3666
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8894 - loss: 0.2872 - val_accuracy: 0.8559 - val_loss: 0.3713
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8885 - loss: 0.2810 - val_accuracy: 0.8559 - val_loss: 0.3727
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8951 - loss: 0.2774 - val_accuracy: 0.8136 - val_loss: 0.3798
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8837 - loss: 0.2719 - val_accuracy: 0.8390 - val_loss: 0.3804
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8856 - loss: 0.2692 - val_accuracy: 0.8475 - val_loss: 0.3786
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8941 - loss: 0.2611 - val_accuracy: 0.8475 - val_loss: 0.3880
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8951 - loss: 0.2609 - val_accuracy: 0.8390 - val_loss: 0.3839
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9026 - loss: 0.2385 - val_accuracy: 0.8220 - val_loss: 0.3912
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9074 - loss: 0.2488 - val_accuracy: 0.8220 - val_loss: 0.3988
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9083 - loss: 0.2509 - val_accuracy: 0.7966 - val_loss: 0.3909
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9017 - loss: 0.2453 - val_accuracy: 0.8136 - val_loss: 0.3919
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8970 - loss: 0.2523 - val_accuracy: 0.8136 - val_loss: 0.3932
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9083 - loss: 0.2352 - val_accuracy: 0.8051 - val_loss: 0.3960
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9102 - loss: 0.2342 - val_accuracy: 0.8051 - val_loss: 0.4079
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9055 - loss: 0.2262 - val_accuracy: 0.8136 - val_loss: 0.4093
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9017 - loss: 0.2346 - val_accuracy: 0.8220 - val_loss: 0.4086
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9083 - loss: 0.2219 - val_accuracy: 0.8220 - val_loss: 0.4124
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9187 - loss: 0.2110 - val_accuracy: 0.7966 - val_loss: 0.4143
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9140 - loss: 0.2053 - val_accuracy: 0.7881 - val_loss: 0.4196
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9216 - loss: 0.2000 - val_accuracy: 0.8136 - val_loss: 0.4255
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9102 - loss: 0.2107 - val_accuracy: 0.8136 - val_loss: 0.4303
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9168 - loss: 0.2040 - val_accuracy: 0.8220 - val_loss: 0.4340
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9206 - loss: 0.2054 - val_accuracy: 0.8220 - val_loss: 0.4353
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9159 - loss: 0.1965 - val_accuracy: 0.8051 - val_loss: 0.4344
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9149 - loss: 0.2010 - val_accuracy: 0.7966 - val_loss: 0.4324
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9225 - loss: 0.1923 - val_accuracy: 0.7966 - val_loss: 0.4324
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9140 - loss: 0.2079 - val_accuracy: 0.8051 - val_loss: 0.4321
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9234 - loss: 0.1952 - val_accuracy: 0.8051 - val_loss: 0.4359
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9338 - loss: 0.1832 - val_accuracy: 0.7966 - val_loss: 0.4413
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9282 - loss: 0.1894 - val_accuracy: 0.7881 - val_loss: 0.4372
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9244 - loss: 0.1808 - val_accuracy: 0.7797 - val_loss: 0.4436
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9386 - loss: 0.1612 - val_accuracy: 0.7966 - val_loss: 0.4499
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9367 - loss: 0.1673 - val_accuracy: 0.7797 - val_loss: 0.4545
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9357 - loss: 0.1825 - val_accuracy: 0.8051 - val_loss: 0.4536
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9357 - loss: 0.1626 - val_accuracy: 0.7966 - val_loss: 0.4644
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9405 - loss: 0.1575 - val_accuracy: 0.7966 - val_loss: 0.4775

In [23]:
loss,accuracy = model.evaluate(x_test_scaled,y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8741 - loss: 0.3717

In [24]:
print(f'Test Loss = {loss:.4f},Test Accuracy={accuracy : .4f}')

Test Loss = 0.3717,Test Accuracy= 0.8741