In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("C:\\Users\\ss\\Desktop\\DL_REGEX\\ANN\\covid_toy - covid_toy.csv")

In [3]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [4]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [5]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [6]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [7]:
x = df.drop(columns=['has_covid'],axis=1)
y = df['has_covid']

In [8]:
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [9]:
categorical_feature = [
    'gender',
    'cough',
    'city'
]

In [10]:
x_encoded = pd.get_dummies(x,columns = categorical_feature,drop_first=True)

In [11]:
x_encoded = x_encoded.astype(int)

In [12]:
lb = LabelEncoder()

In [13]:
y_encoded = lb.fit_transform(y)
y_encoded

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [14]:
x_train, x_test, y_train, y_test = train_test_split(
    x_encoded,
    y_encoded,
    test_size=0.2,
    random_state=42
)

In [15]:
x_train.head()

,age,fever,gender_Male,cough_Strong,city_Delhi,city_Kolkata,city_Mumbai
55,81,101,0,0,0,0,1
88,5,100,0,0,0,1,0
26,19,100,0,0,0,1,0
42,27,100,1,0,1,0,0
69,73,103,0,0,1,0,0

In [16]:
sc = StandardScaler()

In [17]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.fit_transform(x_test)

In [18]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',input_dim = x_train_scaled.shape[1]),  #input
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64,activation='relu'),  #hidden
    tf.keras.layers.Dense(units=1,activation='sigmoid')  #output
])

c:\Users\ss\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [20]:
import tensorflow as tf

learning_rate = 0.001
momentum = 0.9

optimizer = tf.keras.optimizers.SGD(
    learning_rate=learning_rate,
    momentum=momentum,
    nesterov=True
)

In [21]:
model.compile(optimizer=optimizer,loss = loss_fn,metrics = metrics)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [22]:
model.fit(x_train_scaled,y_train,epochs = 50,batch_size = 8,validation_split = 0.1)

Epoch 1/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.5556 - loss: 0.6863 - val_accuracy: 0.6250 - val_loss: 0.6906
Epoch 2/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5139 - loss: 0.6782 - val_accuracy: 0.6250 - val_loss: 0.6897
Epoch 3/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5833 - loss: 0.6635 - val_accuracy: 0.6250 - val_loss: 0.6884
Epoch 4/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5417 - loss: 0.6872 - val_accuracy: 0.5000 - val_loss: 0.6870
Epoch 5/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5833 - loss: 0.6940 - val_accuracy: 0.6250 - val_loss: 0.6864
Epoch 6/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5556 - loss: 0.6779 - val_accuracy: 0.6250 - val_loss: 0.6859
Epoch 7/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5972 - loss: 0.6799 - val_accuracy: 0.5000 - val_loss: 0.6857
Epoch 8/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5278 - loss: 0.6909 - val_accuracy: 0.5000 - val_loss: 0.6855
Epoch 9/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5972 - loss: 0.6806 - val_accuracy: 0.5000 - val_loss: 0.6857
Epoch 10/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5417 - loss: 0.6922 - val_accuracy: 0.5000 - val_loss: 0.6853
Epoch 11/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5278 - loss: 0.6823 - val_accuracy: 0.5000 - val_loss: 0.6843
Epoch 12/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5694 - loss: 0.6811 - val_accuracy: 0.5000 - val_loss: 0.6842
Epoch 13/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5972 - loss: 0.6695 - val_accuracy: 0.5000 - val_loss: 0.6836
Epoch 14/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5417 - loss: 0.6878 - val_accuracy: 0.5000 - val_loss: 0.6846
Epoch 15/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6667 - loss: 0.6691 - val_accuracy: 0.5000 - val_loss: 0.6844
Epoch 16/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 0.6720 - val_accuracy: 0.5000 - val_loss: 0.6838
Epoch 17/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5694 - loss: 0.6751 - val_accuracy: 0.5000 - val_loss: 0.6830
Epoch 18/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6250 - loss: 0.6845 - val_accuracy: 0.5000 - val_loss: 0.6836
Epoch 19/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6111 - loss: 0.6784 - val_accuracy: 0.5000 - val_loss: 0.6831
Epoch 20/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5417 - loss: 0.6914 - val_accuracy: 0.5000 - val_loss: 0.6838
Epoch 21/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5417 - loss: 0.6824 - val_accuracy: 0.5000 - val_loss: 0.6835
Epoch 22/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5556 - loss: 0.6703 - val_accuracy: 0.5000 - val_loss: 0.6828
Epoch 23/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5556 - loss: 0.6633 - val_accuracy: 0.5000 - val_loss: 0.6832
Epoch 24/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5972 - loss: 0.6642 - val_accuracy: 0.5000 - val_loss: 0.6826
Epoch 25/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6389 - loss: 0.6556 - val_accuracy: 0.5000 - val_loss: 0.6820
Epoch 26/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6250 - loss: 0.6608 - val_accuracy: 0.5000 - val_loss: 0.6818
Epoch 27/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6389 - loss: 0.6489 - val_accuracy: 0.5000 - val_loss: 0.6825
Epoch 28/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6111 - loss: 0.6638 - val_accuracy: 0.5000 - val_loss: 0.6824
Epoch 29/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6111 - loss: 0.6634 - val_accuracy: 0.5000 - val_loss: 0.6828
Epoch 30/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6111 - loss: 0.6603 - val_accuracy: 0.5000 - val_loss: 0.6834
Epoch 31/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6389 - loss: 0.6581 - val_accuracy: 0.5000 - val_loss: 0.6832
Epoch 32/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5694 - loss: 0.6604 - val_accuracy: 0.5000 - val_loss: 0.6821
Epoch 33/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5972 - loss: 0.6694 - val_accuracy: 0.5000 - val_loss: 0.6819
Epoch 34/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5417 - loss: 0.6691 - val_accuracy: 0.5000 - val_loss: 0.6821
Epoch 35/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6389 - loss: 0.6489 - val_accuracy: 0.5000 - val_loss: 0.6819
Epoch 36/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6111 - loss: 0.6521 - val_accuracy: 0.5000 - val_loss: 0.6816
Epoch 37/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6250 - loss: 0.6377 - val_accuracy: 0.5000 - val_loss: 0.6821
Epoch 38/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6528 - loss: 0.6396 - val_accuracy: 0.5000 - val_loss: 0.6814
Epoch 39/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6111 - loss: 0.6499 - val_accuracy: 0.5000 - val_loss: 0.6821
Epoch 40/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6389 - loss: 0.6538 - val_accuracy: 0.5000 - val_loss: 0.6814
Epoch 41/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6389 - loss: 0.6501 - val_accuracy: 0.5000 - val_loss: 0.6817
Epoch 42/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5972 - loss: 0.6579 - val_accuracy: 0.5000 - val_loss: 0.6818
Epoch 43/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.6652 - val_accuracy: 0.5000 - val_loss: 0.6816
Epoch 44/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6111 - loss: 0.6680 - val_accuracy: 0.5000 - val_loss: 0.6810
Epoch 45/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6806 - loss: 0.6519 - val_accuracy: 0.5000 - val_loss: 0.6811
Epoch 46/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6667 - loss: 0.6381 - val_accuracy: 0.5000 - val_loss: 0.6814
Epoch 47/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6250 - loss: 0.6375 - val_accuracy: 0.5000 - val_loss: 0.6822
Epoch 48/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6528 - loss: 0.6507 - val_accuracy: 0.5000 - val_loss: 0.6822
Epoch 49/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6806 - loss: 0.6442 - val_accuracy: 0.5000 - val_loss: 0.6812
Epoch 50/50
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6806 - loss: 0.6506 - val_accuracy: 0.5000 - val_loss: 0.6817

In [23]:
loss,accuracy = model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.6500 - loss: 0.6382

In [24]:
print(f'Test Loss = {loss:.4f},Test Accuracy={accuracy : .4f}')

Test Loss = 0.6382,Test Accuracy= 0.6500