In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score

In [7]:
df = pd.read_csv("C:\\Users\\ss\\Desktop\\DL_REGEX\\ANN\\Churn_Modelling - Churn_Modelling.csv")

In [8]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [10]:
x = df.drop(columns=['Exited'],axis=1)
y = df['Exited']

In [11]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [12]:
categorical_feature = ['Surname',
                       'Geography',
                       'Gender']

In [13]:
x_encoded = pd.get_dummies(x,columns = categorical_feature,drop_first=True)

In [14]:
x_encoded = x_encoded.astype(int)

In [16]:
lb = LabelEncoder()

In [17]:
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 1, 1, 0])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(
    x_encoded,
    y_encoded,
    test_size=0.2,
    random_state=42
)

In [20]:
x_train.head()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,...,Surname_Zotova,Surname_Zox,Surname_Zubarev,Surname_Zubareva,Surname_Zuev,Surname_Zuyev,Surname_Zuyeva,Geography_Germany,Geography_Spain,Gender_Male
9254,9255,15601116,686,32,6,0,2,1,1,179093,...,0,0,0,0,0,0,0,0,0,1
1561,1562,15766374,632,42,4,119624,2,1,1,195978,...,0,0,0,0,0,0,0,1,0,1
1670,1671,15716994,559,24,3,114739,1,1,0,85891,...,0,0,0,0,0,0,0,0,1,1
6087,6088,15730759,561,27,9,135637,1,1,0,153080,...,0,0,0,0,0,0,0,0,0,0
6669,6670,15797900,517,56,9,142147,1,0,0,39488,...,0,0,0,0,0,0,0,0,0,1

In [21]:
sc = StandardScaler()

In [22]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.fit_transform(x_test)

In [23]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',input_dim = x_train_scaled.shape[1]),  #input
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64,activation='relu'),  #hidden
    tf.keras.layers.Dense(units=1,activation='sigmoid')  #output
])

c:\Users\ss\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']

In [25]:
import tensorflow as tf

learning_rate = 0.001
momentum = 0.9

optimizer = tf.keras.optimizers.SGD(
    learning_rate=learning_rate,
    momentum=momentum,
    nesterov=True
)

In [26]:
model.compile(optimizer=optimizer,loss = loss_fn,metrics = metrics)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [27]:
model.fit(x_train_scaled,y_train,epochs = 50,batch_size = 8,validation_split = 0.1)

Epoch 1/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7832 - loss: 0.5561 - val_accuracy: 0.7950 - val_loss: 0.5261
Epoch 2/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8067 - loss: 0.4415 - val_accuracy: 0.7887 - val_loss: 0.5152
Epoch 3/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8200 - loss: 0.3935 - val_accuracy: 0.7688 - val_loss: 0.5236
Epoch 4/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8335 - loss: 0.3642 - val_accuracy: 0.7650 - val_loss: 0.5391
Epoch 5/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8378 - loss: 0.3445 - val_accuracy: 0.7700 - val_loss: 0.5594
Epoch 6/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8440 - loss: 0.3325 - val_accuracy: 0.7650 - val_loss: 0.5614
Epoch 7/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8517 - loss: 0.3166 - val_accuracy: 0.7625 - val_loss: 0.5662
Epoch 8/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8546 - loss: 0.3118 - val_accuracy: 0.7613 - val_loss: 0.5751
Epoch 9/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8554 - loss: 0.3066 - val_accuracy: 0.7675 - val_loss: 0.5666
Epoch 10/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8592 - loss: 0.2947 - val_accuracy: 0.7650 - val_loss: 0.5964
Epoch 11/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8611 - loss: 0.2891 - val_accuracy: 0.7650 - val_loss: 0.5890
Epoch 12/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8664 - loss: 0.2857 - val_accuracy: 0.7638 - val_loss: 0.5956
Epoch 13/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8678 - loss: 0.2779 - val_accuracy: 0.7638 - val_loss: 0.6215
Epoch 14/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8649 - loss: 0.2765 - val_accuracy: 0.7538 - val_loss: 0.6196
Epoch 15/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8719 - loss: 0.2684 - val_accuracy: 0.7650 - val_loss: 0.6384
Epoch 16/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8743 - loss: 0.2632 - val_accuracy: 0.7613 - val_loss: 0.6425
Epoch 17/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8776 - loss: 0.2570 - val_accuracy: 0.7563 - val_loss: 0.6486
Epoch 18/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8801 - loss: 0.2482 - val_accuracy: 0.7588 - val_loss: 0.6779
Epoch 19/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8807 - loss: 0.2512 - val_accuracy: 0.7738 - val_loss: 0.6845
Epoch 20/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8876 - loss: 0.2447 - val_accuracy: 0.7700 - val_loss: 0.6747
Epoch 21/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8893 - loss: 0.2379 - val_accuracy: 0.7625 - val_loss: 0.6947
Epoch 22/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8893 - loss: 0.2347 - val_accuracy: 0.7700 - val_loss: 0.7279
Epoch 23/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8935 - loss: 0.2282 - val_accuracy: 0.7713 - val_loss: 0.7300
Epoch 24/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8949 - loss: 0.2246 - val_accuracy: 0.7725 - val_loss: 0.7314
Epoch 25/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8965 - loss: 0.2181 - val_accuracy: 0.7725 - val_loss: 0.7526
Epoch 26/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9006 - loss: 0.2145 - val_accuracy: 0.7700 - val_loss: 0.7615
Epoch 27/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9019 - loss: 0.2044 - val_accuracy: 0.7812 - val_loss: 0.8233
Epoch 28/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9074 - loss: 0.1996 - val_accuracy: 0.7763 - val_loss: 0.8439
Epoch 29/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9069 - loss: 0.1973 - val_accuracy: 0.7688 - val_loss: 0.8326
Epoch 30/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9112 - loss: 0.1930 - val_accuracy: 0.7738 - val_loss: 0.8835
Epoch 31/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9154 - loss: 0.1836 - val_accuracy: 0.7750 - val_loss: 0.8634
Epoch 32/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9164 - loss: 0.1764 - val_accuracy: 0.7763 - val_loss: 0.9307
Epoch 33/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9215 - loss: 0.1705 - val_accuracy: 0.7663 - val_loss: 0.9103
Epoch 34/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9174 - loss: 0.1758 - val_accuracy: 0.7663 - val_loss: 0.9358
Epoch 35/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9279 - loss: 0.1626 - val_accuracy: 0.7725 - val_loss: 0.9975
Epoch 36/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9251 - loss: 0.1644 - val_accuracy: 0.7725 - val_loss: 0.9635
Epoch 37/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9342 - loss: 0.1524 - val_accuracy: 0.7850 - val_loss: 1.0346
Epoch 38/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9322 - loss: 0.1517 - val_accuracy: 0.7812 - val_loss: 1.0321
Epoch 39/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9353 - loss: 0.1478 - val_accuracy: 0.7862 - val_loss: 1.0542
Epoch 40/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9393 - loss: 0.1432 - val_accuracy: 0.7812 - val_loss: 1.0924
Epoch 41/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9408 - loss: 0.1395 - val_accuracy: 0.7900 - val_loss: 1.1153
Epoch 42/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9408 - loss: 0.1345 - val_accuracy: 0.7862 - val_loss: 1.1031
Epoch 43/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.9453 - loss: 0.1244 - val_accuracy: 0.7862 - val_loss: 1.1570
Epoch 44/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9492 - loss: 0.1222 - val_accuracy: 0.7912 - val_loss: 1.1752
Epoch 45/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9483 - loss: 0.1196 - val_accuracy: 0.7800 - val_loss: 1.1784
Epoch 46/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9496 - loss: 0.1172 - val_accuracy: 0.7887 - val_loss: 1.1841
Epoch 47/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9553 - loss: 0.1128 - val_accuracy: 0.7937 - val_loss: 1.2141
Epoch 48/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9506 - loss: 0.1103 - val_accuracy: 0.7950 - val_loss: 1.2610
Epoch 49/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9532 - loss: 0.1099 - val_accuracy: 0.7937 - val_loss: 1.2573
Epoch 50/50
900/900 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9568 - loss: 0.1043 - val_accuracy: 0.7962 - val_loss: 1.2427

In [28]:
loss,accuracy = model.evaluate(x_test_scaled,y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7995 - loss: 0.9321

In [29]:
print(f'Test Loss = {loss:.4f},Test Accuracy={accuracy : .4f}')

Test Loss = 0.9321,Test Accuracy= 0.7995